#Global deployment config
nameOverride: "prometheus-example-app"
fullnameOverride: ""

image:
  repository: 256612512925.dkr.ecr.eu-central-1.amazonaws.com/prometheus-example-app
  pullPolicy: Always
  containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  portName: http

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: prometheus-example-app.production.mytheresa.services
      paths: ["/"]

resources:
  limits:
    cpu: 200m
    memory: 250Mi
  requests:
    cpu: 200m
    memory: 250Mi

replicaCount: 1

hpa:
  MinReplicaCount: 1
  MaxReplicaCount: 1
  ResourceName: "cpu"
  ResourceTarget: 50

nodeSelector:
  "apps-node": "true"

env:
  prometheus-example-app_PORT:   80
  # MYSQL_HOST:     octopus-db-acceptance.cojrrbnlokhb.eu-central-1.rds.amazonaws.com
  # MYSQL_PORT:     3306
  # MYSQL_DATABASE: octopus
  # MYSQL_USER:     mytadmin
  # AWS_REGION:     eu-central-1
  # SNS_ARN:        arn:aws:sns:eu-central-1:256612512925:octopus-stage-topic-acceptance
  # SQS_SERVICES_QUEUE_URL: https://sqs.eu-central-1.amazonaws.com/256612512925/octopus-service-register-queue-acceptance.fifo
  # OCTOPUS_PAST_STAGES : 1
  # OCTOPUS_FUTURE_STAGES : 2

# ssm:
#   /octopus/acceptance/db_password: MYSQL_PASSWORD

argo_rollout: false

serviceAccountName: octopus-svc
