#Global deployment config
nameOverride: ""
fullnameOverride: ""

image:
  repository: marcportabellaclotet/prometheus-example-app
  pullPolicy: Always
  containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  portName: http

nodeSelector: {}

replicaCount: 1

ingress:
  className: public

hpa: {}

timeout: 120

podSecurityContext : {}
