{{- if .Values.ingress.enabled -}}
{{- $fullName := include "prometheus-example-app.fullname" . -}}
{{- $svcPortName := .Values.service.portName -}}
{{- $timeout := .Values.timeout -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "prometheus-example-app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ $timeout |default 120 }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ $timeout |default  120 }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ $timeout |default 120 }}"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ $svcPortName }}
        {{- end }}
  {{- end }}
{{- end }}
