apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: {{ include "prometheus-example-app.fullname" . }}-{{ .Values.environment }}
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  service: "prometheus-example-app"
  labels:
    owner: "myteam"
    repo: "myorg/myservice"
    tier: "2"
  slos:
    - name: "requests-availability"
      objective: 95
      description: "Common SLO based on availability for HTTP request responses."
      sli:
        events:
          errorQuery: sum(rate(nginx_ingress_controller_requests{status=~"(5..|429|404)",ingress="prometheus-example-app",exported_namespace="{{ .Values.environment }}"}}[{{`{{.window }}`}}]))
          totalQuery: sum(rate(nginx_ingress_controller_requests{ingress="prometheus-example-app",exported_namespace="{{ .Values.environment }}"}[{{`{{.window }}`}}]))
      alerting:
        name: MyServiceHighErrorRate
        labels:
          category: "availability"
        annotations:
          summary: "High error rate on 'myservice' requests responses"
        pageAlert:
          labels:
            severity: pageteam
            routing_key: myteam
        ticketAlert:
          labels:
            severity: "slack"
            slack_channel: "#alerts-myteam"
    - name: "requests-latency"
      objective: 95
      description: "Common SLO based on latency for HTTP request responses."
      labels:
        category: latency
      sli:
        events:
          errorQuery: |
            (
              sum(rate(nginx_ingress_controller_response_duration_seconds_count{ingress="prometheus-example-app",,exported_namespace="{{ .Values.environment }}"}}[{{`{{.window }}`}}]))
              -
              sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress="prometheus-example-app",le="0.5",,exported_namespace="{{ .Values.environment }}"}}[{{`{{.window }}`}}]))
            )
          totalQuery: sum(rate(nginx_ingress_controller_response_duration_seconds_count{ingress="prometheus-example-app",,exported_namespace="{{ .Values.environment }}"}}[{{`{{.window }}`}}]))
      alerting:
        name: MyServiceHighLatency
        labels:
          category: "latency"
        annotations:
          summary: "High error rate on 'myservice' requests responses"
        pageAlert:
          labels:
            severity: pageteam
            routing_key: myteam
        ticketAlert:
          labels:
            severity: "slack"
            slack_channel: "#alerts-myteam"