apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-prometheus-example-app
  namespace: argocd
  labels:
    type: argocd-appconfig
    application: prometheus-example-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/applications/dev
    repoURL: https://github.com/marcportabellaclotet-mt/prometheus-example-app-deploy.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-prometheus-example-app
  namespace: argocd
  labels:
    type: argocd-appconfig
    application: buy-domain
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/applications/test
    repoURL: https://github.com/marcportabellaclotet-mt/prometheus-example-app-deploy.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-prometheus-example-app
  namespace: argocd
  labels:
    type: argocd-appconfig
    application: prometheus-example-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/applications/prod
    repoURL: https://github.com/marcportabellaclotet-mt/prometheus-example-app-deploy.git
    targetRevision: HEAD
