environment: prod
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: totmicro-issuer
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: prometheus-example-app-prod.totmicro.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: prometheus-example-app-prod-tls
      hosts:
        - prometheus-example-app-prod.totmicro.com